describe('Marketplace', () => {
  it('Should return true when title component was correct', () => {
    cy.visit('/')
    cy.contains('Escolha um serviço').should('to.have.length', 1)
    cy.contains('Web').should('to.have.length', 1)
    cy.contains('Banco de dados').should('to.have.length', 1)
  })

  it('When click in Criar meu Wordpress and don`t fill out the Criação de serviço, show a message', () => {
    cy.visit('/')
    cy.contains('Criar meu Wordpress').click()
    cy.contains('Criar meu wordpress').click()
  })

  it('When click in Criar meu Wordpress and fill out the Criação de serviço, a new Wordpress must be created', () => {
    cy.visit('/')
    cy.contains('Criar meu Wordpress').click()
    cy.get('#subdomain').type('test')
    cy.get('#user').type('Testing')
    cy.get('#password').type('123456')
    cy.get('#passwordConfirmation').type('123456')
    cy.contains('Criar meu wordpress').click()
    cy.contains('Detalhes da criação do serviço wordpress').should('to.have.length', 1)
    cy.contains('Status').should('to.have.length', 1)
    cy.contains('Status do cluster').should('to.have.length', 1)
    cy.contains('Logs das instâncias').should('to.have.length', 1)
    cy.contains('Detalhes').should('to.have.length', 1)
    cy.get('.align-itens-start > :nth-child(2) > .row > :nth-child(2)').contains('wordpress').should('to.have.length', 1)
    cy.get(':nth-child(4) > a').contains('test').should('to.have.length', 1)
    cy.contains('Meus Serviços').click()
    cy.get('tr > :nth-child(1) > a').click()
    cy.contains('Detalhes da criação do serviço wordpress').should('to.have.length', 1)
    cy.contains('Status').should('to.have.length', 1)
    cy.contains('Status do cluster').should('to.have.length', 1)
    cy.contains('Logs das instâncias').should('to.have.length', 1)
    cy.contains('Detalhes').should('to.have.length', 1)
    cy.get('.align-itens-start > :nth-child(2) > .row > :nth-child(2)').contains('wordpress').should('to.have.length', 1)
    cy.get(':nth-child(4) > a').contains('test').should('to.have.length', 1)
  })
})