name: Marketplace Tests - Complete Project

on:
  push:
    branches:
      - main
    paths:
      - 'cypress/**.jsx'
      - 'cypress/**.js'
      - 'cypress/**.yml'

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.0

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress

      -name: Run Marketplace
        working-directory: ./
        start: npm run dev
        wait-on: 'npx wait-on --timeout 5000 http://localhost:3000'

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./cypress
 